apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-engine
  labels:
    app: ns-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns-engine
  template:
    metadata:
      labels:
        app: ns-engine
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z -w 2 nats 4222; do echo "Waiting for NATS..."; sleep 2; done;']
        - name: wait-for-clickhouse
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z -w 2 clickhouse 9000; do echo "Waiting for ClickHouse..."; sleep 2; done;']
        - name: wait-for-ns-ai
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z -w 2 ns-ai 50052; do echo "Waiting for ns-ai service..."; sleep 2; done;']
      containers:
        - name: ns-engine
          image: decadeqzj/ns-engine:v1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-volume
              mountPath: /configs/
          envFrom:
            - secretRef:
                name: go2netspectra-secret
          resources:
            requests:
              cpu: 1
              memory: 128Mi
            limits:
              cpu: 4
              memory: 1024Mi
      volumes:
        - name: config-volume
          configMap:
            name: go2netspectra-config
