apiVersion: v1
kind: Service
metadata:
  name: ns-api
  labels:
    app: ns-api
spec:
  selector:
    app: ns-api
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      nodePort: 30051
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
