apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  config.xml: |
    <yandex>
      <logger>
        <level>information</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
      </logger>
    </yandex>

  clusters.xml: |
    <yandex>
      <remote_servers>
        <cluster1>
          <shard>
            <replica>
              <host>clickhouse-0.clickhouse.default.svc.cluster.local</host>
              <port>9000</port>
            </replica>
            <replica>
              <host>clickhouse-1.clickhouse.default.svc.cluster.local</host>
              <port>9000</port>
            </replica>
            <replica>
              <host>clickhouse-2.clickhouse.default.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </cluster1>
      </remote_servers>
    </yandex>