# Configuration file for the network traffic aggregator system.
aggregator:

  # Type of aggregator to use. Currently only "exact" is supported.
  type: "exact"

  # The overall measurement period. At the end of each period, all task data is reset.
  # This should be longer than or equal to the longest writer snapshot_interval.
  period: "10m"

  # Global settings for the aggregator engine

  # Number of worker goroutines to process incoming packets.
  num_workers: 16
  # Size of the channel buffer for incoming packets.
  size_of_packet_channel: 10000

  # Configuration block for the "exact" aggregator type
  exact:
    # All tasks within this block share this snapshot interval and writer list.
    writers:
      - type: "gob"
        enabled: true
        snapshot_interval: "3600s"
        gob:
          root_path: "test/res"
      - type: "clickhouse"
        enabled: false
        snapshot_interval: "3600s"
        clickhouse:
          host: "localhost"
          port: 9000
          database: "default"
          username: "default"
          password: ""
    # List of specific aggregation tasks to run.
    tasks:
        - name: "per_src_ip"
          key_fields: ["SrcIP"]
          num_shards: 64
        - name: "per_dst_ip"
          key_fields: ["DstIP"]
          num_shards: 64
        - name: "per_src_port"
          key_fields: ["SrcPort"]
          num_shards: 32
        - name: "per_dst_port"
          key_fields: ["DstPort"]
          num_shards: 32
        - name: "per_protocol"
          key_fields: ["Protocol"]
          num_shards: 16
        - name: "per_five_tuple"
          key_fields: ["SrcIP", "DstIP", "SrcPort", "DstPort", "Protocol"]
          num_shards: 128