aggregator:
  num_workers: 16
  size_of_packet_channel: 8096
  snapshot_interval: "7200s"
  storage_root_path: "./test/res"
  type: exact
  exact_tasks:
    - name: "per_src_ip"
      key_fields: ["SrcIP"]
      num_shards: 64
    - name: "per_dst_ip"
      key_fields: ["DstIP"]
      num_shards: 64
    - name: "per_src_port"
      key_fields: ["SrcPort"]
      num_shards: 32
    - name: "per_dst_port"
      key_fields: ["DstPort"]
      num_shards: 32
    - name: "per_protocol"
      key_fields: ["Protocol"]
      num_shards: 16
    - name: "per_five_tuple"
      key_fields: ["SrcIP", "DstIP", "SrcPort", "DstPort", "Protocol"]
      num_shards: 128
