{{- if .Values.nats.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "go2netspectra.fullname" . }}-nats
  labels:
    {{- include "go2netspectra.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  serviceName: {{ include "go2netspectra.fullname" . }}-nats
  replicas: {{ .Values.nats.replicaCount }}
  selector:
    matchLabels:
      {{- include "go2netspectra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nats
  template:
    metadata:
      labels:
        {{- include "go2netspectra.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nats
    spec:
      containers:
        - name: nats
          image: "{{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}"
          imagePullPolicy: {{ .Values.nats.image.pullPolicy }}
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 6222
              name: cluster
            - containerPort: 8222
              name: monitoring
          command:
            - "/bin/sh"
            - "-ec"
            - "nats-server --config /configs/nats.conf --cluster_advertise $POD_IP:6222"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config-volume
              mountPath: /configs/
          resources:
            {{- toYaml .Values.nats.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "go2netspectra.fullname" . }}-nats-config
{{- end }}
