{{- if .Values.nsEngine.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go2netspectra.fullname" . }}-ns-engine
  labels:
    {{- include "go2netspectra.labels" . | nindent 4 }}
    app.kubernetes.io/component: ns-engine
spec:
  replicas: {{ .Values.nsEngine.replicaCount }}
  selector:
    matchLabels:
      {{- include "go2netspectra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ns-engine
  template:
    metadata:
      labels:
        {{- include "go2netspectra.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ns-engine
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z -w 2 {{ include "go2netspectra.fullname" . }}-nats 4222; do echo "Waiting for NATS..."; sleep 2; done;']
        - name: wait-for-clickhouse
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z -w 2 {{ include "go2netspectra.fullname" . }}-clickhouse 9000; do echo "Waiting for ClickHouse..."; sleep 2; done;']
      containers:
        - name: ns-engine
          image: "{{ .Values.nsEngine.image.repository }}:{{ .Values.nsEngine.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nsEngine.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /configs/
          envFrom:
            - secretRef:
                name: {{ include "go2netspectra.fullname" . }}-secret
          resources:
            {{- toYaml .Values.nsEngine.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "go2netspectra.fullname" . }}-config
{{- end }}
