apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go2netspectra.fullname" . }}-secret
  labels:
    {{- include "go2netspectra.labels" . | nindent 4 }}
type: Opaque
stringData:
  # --- Hardcoded Internal Service Endpoints ---
  API_GRPC_LISTEN_ADDR: "0.0.0.0:50051"
  API_HTTP_LISTEN_ADDR: "0.0.0.0:8080"
  AI_GRPC_LISTEN_ADDR: "0.0.0.0:50052"
  NATS_URL: "{{ include "go2netspectra.fullname" . }}-nats:4222"
  ALERTER_AI_SERVICE_ADDR: "{{ include "go2netspectra.fullname" . }}-ns-ai:50052"
  CLICKHOUSE_HOST: "{{ include "go2netspectra.fullname" . }}-clickhouse"
  CLICKHOUSE_PORT: "9000"

  # --- User-configurable sensitive values from values.yaml ---
  AI_API_KEY: {{ .Values.config.ai.api_key | quote }}
  AI_BASE_URL: {{ .Values.config.ai.base_url | quote }}

  SMTP_HOST: {{ .Values.config.smtp.host | quote }}
  SMTP_PORT: {{ .Values.config.smtp.port | quote }}
  SMTP_USER: {{ .Values.config.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.config.smtp.password | quote }}
  SMTP_FROM: {{ .Values.config.smtp.from | quote }}
  SMTP_TO: {{ .Values.config.smtp.to | quote }}

  CLICKHOUSE_DB: "default"
  CLICKHOUSE_USERNAME: "default"
  CLICKHOUSE_PASSWORD: "123"
